import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate, Trend } from 'k6/metrics';

const BASE_URL = __ENV.BASE_URL || 'http://backend:4000';

// Custom metrics
const errorRate = new Rate('errors');
const readLatency = new Trend('read_latency', true);
const writeLatency = new Trend('write_latency', true);

export const options = {
  stages: [
    { duration: '1m', target: 20 }, // 워밍업
    { duration: '2m', target: 50 }, // 목표 부하
    { duration: '5m', target: 50 }, // 유지
    { duration: '1m', target: 100 }, // 피크 테스트
    { duration: '1m', target: 0 }, // 램프다운
  ],
  thresholds: {
    // 전역 임계값
    http_req_duration: ['p(95)<500', 'p(99)<1000'],
    http_req_failed: ['rate<0.02'], // 2% 에러율 허용
    errors: ['rate<0.05'],

    // 엔드포인트별 임계값 (의사결정 사항 반영)
    'http_req_duration{endpoint:posts_list}': ['p(95)<200'],
    'http_req_duration{endpoint:post_detail}': ['p(95)<150'],
    'http_req_duration{endpoint:create_post}': ['p(95)<1000'],

    // RPS 목표
    'http_reqs{endpoint:posts_list}': ['rate>=30'], // 최소 30 RPS
    'http_reqs{endpoint:post_detail}': ['rate>=30'],
  },
};

// 테스트 사용자 토큰 (setup 단계에서 획득)
export function setup() {
  // 테스트 시작 전 로그인하여 토큰 획득
  const loginRes = http.post(
    `${BASE_URL}/auth/login`,
    JSON.stringify({
      email: 'loadtest@example.com',
      password: 'TestPassword123!',
    }),
    { headers: { 'Content-Type': 'application/json' } },
  );

  if (loginRes.status === 200) {
    try {
      const { accessToken } = JSON.parse(loginRes.body);
      return { token: accessToken };
    } catch (e) {
      console.warn('Failed to parse login response, using mock token for read-only tests');
      return { token: null };
    }
  }

  console.warn('Authentication failed, running read-only tests');
  return { token: null };
}

export default function (data) {
  const scenario = Math.random();

  // 90:10 읽기:쓰기 비율
  if (scenario < 0.5) {
    // 50% - 전체 게시글 목록 조회
    const res = http.get(`${BASE_URL}/posts`, {
      tags: { endpoint: 'posts_list' },
    });

    readLatency.add(res.timings.duration);

    check(res, {
      'posts list status is 200': (r) => r.status === 200,
      'has posts array': (r) => {
        try {
          return Array.isArray(JSON.parse(r.body));
        } catch {
          return false;
        }
      },
    }) || errorRate.add(1);
  } else if (scenario < 0.9) {
    // 40% - 특정 게시글 조회
    const postId = Math.floor(Math.random() * 100) + 1;
    const res = http.get(`${BASE_URL}/posts/${postId}`, {
      tags: { endpoint: 'post_detail' },
    });

    readLatency.add(res.timings.duration);

    check(res, {
      'post detail status is 200 or 404': (r) => [200, 404].includes(r.status),
    }) || errorRate.add(1);
  } else if (data.token) {
    // 10% - 게시글 작성 (인증 필요)
    const payload = JSON.stringify({
      title: `Load Test Post ${Date.now()}`,
      content: `Generated by k6 at ${new Date().toISOString()}`,
    });

    const res = http.post(`${BASE_URL}/posts`, payload, {
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${data.token}`,
      },
      tags: { endpoint: 'create_post' },
    });

    writeLatency.add(res.timings.duration);

    check(res, {
      'create post status is 201': (r) => r.status === 201,
      'created post has id': (r) => {
        try {
          return JSON.parse(r.body).id !== undefined;
        } catch {
          return false;
        }
      },
    }) || errorRate.add(1);
  }

  sleep(1);
}

export function teardown(data) {
  console.log('✅ Load test completed');
}

export function handleSummary(data) {
  const metrics = data.metrics;

  console.log('\n📊 Load Test Results');
  console.log('════════════════════════════════════════');
  console.log(`Total Requests:     ${metrics.http_reqs.count}`);
  console.log(`Request Rate:       ${metrics.http_reqs.values.rate.toFixed(2)} req/s`);
  console.log(
    `Error Rate:         ${(metrics.http_req_failed.values.rate * 100).toFixed(2)}%`,
  );
  console.log('────────────────────────────────────────');
  console.log(
    `p50 Latency:        ${metrics.http_req_duration.values['p(50)'].toFixed(2)}ms`,
  );
  console.log(
    `p95 Latency:        ${metrics.http_req_duration.values['p(95)'].toFixed(2)}ms`,
  );
  console.log(
    `p99 Latency:        ${metrics.http_req_duration.values['p(99)'].toFixed(2)}ms`,
  );
  console.log(`Max Latency:        ${metrics.http_req_duration.values.max.toFixed(2)}ms`);
  console.log('────────────────────────────────────────');

  if (metrics.read_latency) {
    console.log(
      `Read p95:           ${metrics.read_latency.values['p(95)'].toFixed(2)}ms`,
    );
  }

  if (metrics.write_latency) {
    console.log(
      `Write p95:          ${metrics.write_latency.values['p(95)'].toFixed(2)}ms`,
    );
  }

  console.log('════════════════════════════════════════');

  // Endpoint별 통계
  console.log('\n📈 Endpoint Statistics:');

  const endpointStats = {};
  for (const [key, value] of Object.entries(metrics)) {
    if (key.includes('endpoint:')) {
      const match = key.match(/endpoint:(\w+)/);
      if (match) {
        const endpoint = match[1];
        if (!endpointStats[endpoint]) {
          endpointStats[endpoint] = {};
        }

        if (key.includes('http_req_duration')) {
          endpointStats[endpoint].p95 = value.values['p(95)'].toFixed(2);
        }
        if (key.includes('http_reqs')) {
          endpointStats[endpoint].rps = value.values.rate.toFixed(2);
        }
      }
    }
  }

  for (const [endpoint, stats] of Object.entries(endpointStats)) {
    console.log(`  ${endpoint}:`);
    if (stats.rps) console.log(`    RPS: ${stats.rps}`);
    if (stats.p95) console.log(`    p95: ${stats.p95}ms`);
  }

  console.log('\n');

  return {
    stdout: JSON.stringify(data, null, 2),
  };
}
